_parent_: projects/neuralangelo/configs/base.yaml
data:
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 0.8
    root: datasets/Bamboo_ds2
    train:
        image_size:
        - 7690
        - 5134
    type: projects.neuralangelo.data
    val:
        image_size:
        - 449
        - 300
model:
    appear_embed:
        enabled: false
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 4
            mlp:
                inside_out: false
