_parent_: projects/neuralangelo/configs/base.yaml
data:
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: datasets/WoodenFruitBox_ds2
    train:
        image_size:
        - 3992
        - 3002
    type: projects.neuralangelo.data
    val:
        image_size:
        - 398
        - 300
model:
    appear_embed:
        enabled: false
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 4
            mlp:
                inside_out: false
